# .slather.yml

coverage_service: cobertura_xml
configuration: Debug
xcodeproj: ./AppleSearchAPIDemo.xcodeproj
scheme: AppleSearchAPIDemo
source_directory: ./AppleSearchAPIDemo
ignore:
  - "ThirdParty/*
