# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main

pool:
  vmImage: 'macos-10.14'

variables:
  - name: configuration
    value: 'Debug'
  - name: sdk
    value: 'iphoneos'

name: 'Clean and Build_Build_Id_$(Build.BuildId)_$(Date:yyyy-MM-dd hh-mm-ss)UTC_$(Rev:r)'

steps:
- task: Xcode@5
  inputs:
    actions: 'clean build'
    scheme: 'AppleSearchAPIDemo'
    sdk: '$(sdk)'
    configuration: '$(configuration)'
    xcWorkspacePath: '**/*.xcodeproj/project.xcworkspace'
    xcodeVersion: 'default'
